### ISSUE TITLE
Aligning images next to each other

### ISSUE THREAD

**Issue by emmawooten12** [benmiller314/cdm2020spring#11]
**The challenge**
I am trying to place images next to each other in a row rather than on top of each other on the homepage.

**Files involved**
https://github.com/emmawooten12/website-portfolio-2020spring and I am working on home-page.html with images IMG_5713.jpg, IMG_4651.jpg, and IMG_4826.jpg.

**Steps you've taken**
I have tried (as seen in the screenshot) just using different classes to align them, and also some image aligning in the .css file but nothing has worked.

**Screenshots**
<img width="739" alt="Screen Shot 2020-03-24 at 3 52 39 PM" src="https://user-images.githubusercontent.com/59624297/77470724-871e3c00-6de7-11ea-9244-a03d28edb7fe.png">

**What systems are you using?**
I'm on a Mac and opening these pages in Chrome

**Comment by benmiller314** [comment]
Thanks for posting this question, Emma! It's a good one to answer on the forum, because this is a common task that a lot of people will probably want to know how to do. And it's fairly straightforward to achieve your goal, using flexbox.

We'll wrap the images in a &lt;div&gt;, which essentially just groups them together; then we'll create a rule that says, "This group is a flexbox." 

![The key css rule is 'display: flex'; It has to be applied to a container to affect items inside the container.](https://user-images.githubusercontent.com/3182049/77493277-13952280-6e19-11ea-949a-38946f5ca0b3.png)

Having done that, all the direct children of the container – in this case, the three &lt;img&gt;es – jump up into a row. (We could also make this a column by declaring `flex-direction: column;` but by default, `flex-direction` is presumed to be `row`.)

![Images will move to a horizontal row, but will not have an alignment (unless one of the items is aligned separately).](https://user-images.githubusercontent.com/3182049/77493509-b8176480-6e19-11ea-851f-43eb76457166.png)

We can then add more rules to the flex container (our div.row) to control the spacing. The primary axis (in our case, horizontal) is controlled with the `justify-content` CSS attribute; Atom or your browser's inspector will tell you the <a href="https://css-tricks.com/snippets/css/a-guide-to-flexbox/" title="A complete guide to Flexbox; search for 'justify-content'">many values</a> it can take. In our case, `justify-content: center;` will cluster them in the middle, and you can then add some margin to the images, if you want. (The selector `.row img` will catch them all.) Or try `justify-content: space-around;` to let the browser figure out spacing on its own.

**With center:**
![flexbox--center](https://user-images.githubusercontent.com/3182049/77494087-36c0d180-6e1b-11ea-8890-439a37214ee5.png)

**With space-around:**
![flexbox--space-around](https://user-images.githubusercontent.com/3182049/77494095-3d4f4900-6e1b-11ea-8d8c-165310132550.png)



And that's just about it! You may want to add some padding and max-width to body to help with the spacing around these particular images, but that's separate from this question. 


**NB: I've also recorded this in action with voiceover [as a screencast](https://pitt.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=bd2f6e85-ddbc-486d-8f92-ab8900188039);** click that link to view.
